# Generated by Django 5.2.15 on 2026-06-12 22:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2026, 6, 12, 22, 21, 33, 36135, tzinfo=datetime.timezone.utc))),
                ('calories', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'day'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'day'), name='unique_calorie_owner_day')],
            },
        ),
    ]
