# Generated by Django 5.2.15 on 2026-06-12 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.DateField(default=datetime.datetime(2026, 6, 12, 22, 22, 42, 674408, tzinfo=datetime.timezone.utc)),
        ),
    ]
