# Generated by Django 5.2.15 on 2026-06-12 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
