# Generated by Django 5.2.15 on 2026-06-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_day'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='food',
            name='unique_calorie_owner_day',
        ),
    ]
