# Generated by Django 5.2.15 on 2026-06-24 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_remove_food_unique_calorie_owner_day'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FoodGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.PositiveIntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_goal', to='goals.usergoals')),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
    ]
