# Generated by Django 5.2.15 on 2026-06-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
