# Generated by Django 5.2.15 on 2026-06-11 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_workout_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unq_ownr_wkt_name'),
        ),
    ]
