# Generated by Django 5.2.15 on 2026-06-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_workout_unq_ownr_wkt_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
