# Generated by Django 5.2.15 on 2026-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
            ],
        ),
    ]
