# Generated by Django 5.2.15 on 2026-06-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepcount',
            options={'ordering': ['day']},
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
