# Generated by Django 5.2.15 on 2026-06-07 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_stepcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepcount',
            name='day',
            field=models.DateField(default=datetime.datetime(2026, 6, 7, 14, 30, 15, 932540, tzinfo=datetime.timezone.utc), verbose_name='day'),
            preserve_default=False,
        ),
    ]
