# Generated by Django 5.2.15 on 2026-06-11 01:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_stepcount_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcount',
            name='day',
            field=models.DateField(default=datetime.datetime(2026, 6, 11, 1, 15, 55, 403295, tzinfo=datetime.timezone.utc), verbose_name='day'),
        ),
        migrations.AddConstraint(
            model_name='stepcount',
            constraint=models.UniqueConstraint(fields=('owner', 'day'), name='unique_owner_steps_day'),
        ),
    ]
