# Generated by Django 5.2.15 on 2026-06-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_stepcount_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcount',
            name='day',
            field=models.DateField(unique=True, verbose_name='day'),
        ),
    ]
