# Generated by Django 5.2.15 on 2026-06-11 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_alter_stepcount_day_stepcount_unique_owner_steps_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcount',
            name='day',
            field=models.DateField(default=datetime.datetime(2026, 6, 11, 1, 17, 12, 963774, tzinfo=datetime.timezone.utc), verbose_name='day'),
        ),
    ]
