# Generated by Django 5.2.15 on 2026-06-12 20:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0005_alter_stepcount_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stepcount',
            name='unique_owner_steps_day',
        ),
        migrations.AlterField(
            model_name='stepcount',
            name='day',
            field=models.DateField(default=datetime.datetime(2026, 6, 12, 20, 10, 22, 79094, tzinfo=datetime.timezone.utc), verbose_name='day'),
        ),
        migrations.AddConstraint(
            model_name='stepcount',
            constraint=models.UniqueConstraint(fields=('owner', 'day', 'steps'), name='unique_owner_steps_day'),
        ),
    ]
