# Generated by Django 5.2.15 on 2026-06-12 22:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_remove_stepcount_unique_owner_steps_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
        migrations.AlterModelOptions(
            name='stepcount',
            options={'ordering': ['day', 'owner']},
        ),
        migrations.RemoveConstraint(
            model_name='stepcount',
            name='unique_owner_steps_day',
        ),
        migrations.RemoveField(
            model_name='stepcount',
            name='goal',
        ),
        migrations.AlterField(
            model_name='stepcount',
            name='day',
            field=models.DateField(default=datetime.datetime(2026, 6, 12, 22, 21, 32, 659076, tzinfo=datetime.timezone.utc), verbose_name='day'),
        ),
        migrations.AddConstraint(
            model_name='stepcount',
            constraint=models.UniqueConstraint(fields=('owner', 'day'), name='unique_owner_steps_day'),
        ),
        migrations.AddField(
            model_name='stepgoal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_goal', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
