# Generated by Django 5.2.15 on 2026-06-12 22:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_stepgoal_alter_stepcount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcount',
            name='day',
            field=models.DateField(default=datetime.datetime(2026, 6, 12, 22, 22, 42, 318608, tzinfo=datetime.timezone.utc), verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='stepgoal',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_goal', to=settings.AUTH_USER_MODEL),
        ),
    ]
