# Generated by Django 5.2.15 on 2026-06-12 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0008_alter_stepcount_day_alter_stepgoal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcount',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='day'),
        ),
    ]
