# Generated by Django 5.2.15 on 2026-06-24 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('steps', '0009_alter_stepcount_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcount',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stepgoal',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_goal', to='goals.usergoals'),
        ),
    ]
