# Generated by Django 5.2.15 on 2026-06-12 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('running', 'running'), ('walking', 'walking'), ('cycling', 'cycling'), ('sit-up', 'sit-up'), ('bench press', 'bench press')])),
                ('duration', models.DurationField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time', 'type', 'duration'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unq_ownr_wkt_name')],
            },
        ),
    ]
