# Generated by Django 5.2.15 on 2026-06-24 23:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='metric',
            field=models.CharField(choices=[('REPS', 'repitions'), ('LBS', 'Pounds'), ('KG', 'kilograms'), ('MIN', 'minutes'), ('HR', 'hours'), ('MI', 'miles'), ('KM', 'kilometers')], default='REPS', help_text='Measuring Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(help_text='Name of workout', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='date/time workout started'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('RN', 'running'), ('WK', 'walking'), ('CY', 'cycling'), ('SU', 'sit-up'), ('BP', 'bench-press'), ('SQ', 'squat'), ('DL', 'deadlift')], help_text='workout type'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('metric__in', [['KM', 'MI'], ['MIN', 'HR']]), ('type__in', ['RN', 'WK'])), models.Q(('metric__in', [['REPS'], ['KG', 'LBS']]), ('type__in', ['SQ', 'BP', 'DL'])), models.Q(('metric__in', [['REPS']]), ('type__in', ['SU'])), _connector='OR'), name='valid_workout_metric_combo'),
        ),
    ]
