# Generated by Django 5.2.15 on 2026-06-24 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('workouts', '0002_workout_metric_alter_workout_name_alter_workout_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RN', 'running'), ('WK', 'walking'), ('CY', 'cycling'), ('SU', 'sit-up'), ('BP', 'bench-press'), ('SQ', 'squat'), ('DL', 'deadlift')], help_text='workout type')),
                ('metric', models.CharField(choices=[('REPS', 'repitions'), ('LBS', 'Pounds'), ('KG', 'kilograms'), ('MIN', 'minutes'), ('HR', 'hours'), ('MI', 'miles'), ('KM', 'kilometers')], help_text='measuring type')),
                ('goal', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_goal', to='goals.usergoals')),
            ],
            options={
                'ordering': ['owner'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('metric__in', [['KM', 'MI'], ['MIN', 'HR']]), ('type__in', ['RN', 'WK'])), models.Q(('metric__in', [['REPS'], ['KG', 'LBS']]), ('type__in', ['SQ', 'BP', 'DL'])), models.Q(('metric__in', [['REPS']]), ('type__in', ['SU'])), _connector='OR'), name='valid_workout_metric_combo_goal')],
            },
        ),
    ]
